alias(
    name = "models",
    actual = "//cookbook/models/src/main:models",
    visibility = ["//visibility:public"],
)

test_suite(
    name = "checkin_tests",
    tests = [
        "//cookbook/models/src/test:recipe_egg_test",
        "//cookbook/models/src/test:recipe_test",
    ],
)
