load("@bazel_latex//:latex.bzl", "latex_document")

latex_document(
  name = "resume",
  srcs = [
    "@bazel_latex//packages:array",
    "@bazel_latex//packages:enumitem",
    "@bazel_latex//packages:geometry",
  ],
  main = "resume.ltx",
)
